---
title: "Binning Flow Plots of Interest R3-HA vs pSMAD"
author: "Wisam"
date: "2025-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flowCore)
```

```{r}
# Loading FCS File test
df_R_10T = read.FCS("Data/TGFB1/2023-07-19/R3_10T.fcs")
df_L_0T = read.FCS("Data/TGFB1/2023-07-19/Luc_0T.fcs")
```
```{r}
df_new_R_10T = read.FCS("Data/TGFB1/2024-09-04/R3_10T.fcs", alter.names = TRUE)
df_new_L_0T = read.FCS("Data/TGFB1/2024-09-04/Luc_0T.fcs", alter.names = TRUE)
```

```{r}
summary(df_new_R_10T)
```



```{r}
# Path to your folder with .fcs files
data_dir <- "Data/TGFB1/2024-09-04/"

# Get all FCS files in the folder (recursive = TRUE if subfolders)
fcs_files <- list.files(data_dir, pattern = "\\.fcs$", full.names = TRUE)

# Read all FCS files into a flowSet
fs <- read.flowSet(files = fcs_files, transformation = FALSE, alter.names = TRUE)

# Extract base file names (without extension or path)
sample_names <- tools::file_path_sans_ext(basename(fcs_files))

# Assign these names to the samples in the flowSet
sampleNames(fs) <- sample_names

# Check the names
sampleNames(fs)
```
```{r}
library(ggcyto)
fs_sample = fs[["Luc_0T"]]

plot(exprs(fs_sample)[,c("FSC.A", "SSC.A")],
     pch = ".", main = "FSC vs SSC", xlab = "FSC-A", ylab = "SSC-A")j


autoplot(fs, x = "B1.A", y = "YG1.A") +
  scale_x_log10() +
  scale_y_log10()
        
```

```{r}
library(flowViz)

xyplot(`SSC.A` ~ `FSC.A`, fs_sample,
       smooth = FALSE,
        filter = NULL,
       par.settings = list(gate.fill = "green"),
       xbin = 128,
       main = "FSC vs SSC across samples")

xyplot(`YG1.A` ~ `B1.A`, fs_sample,
       smooth = FALSE,
       filter = NULL,
       par.settings = list(gate.fill = "transparent"),
       xbin = 128,
       main = "pSMAD2 vs HA")
```
```{r}
# Load required packages
library(CytoExploreR)
library(CytoExploreRData)
```




