```{r setup, include=FALSE}
library(tidyverse)
library(fs)
```


```{r helper-functions}
source("2L_helper.R")

```

```{r load-in-single-experiment, include=FALSE}
# Load in Singlet and DAPI gated data
all_exp_data = loadAllTwoLigandData("Test Run")
```


```{r load-in-single-experiment, include=FALSE}
df = run_bootstrap_analysis_pipeline(all_exp_data,
                                           pSMAD2_perc_cutoff = 0,
                                           HA_perc_cutoff = 0.95,
                                           n_bins = 10,
                                           n_boot = 1000)
```



```{r}
temp = df$binned_boot %>%
  filter(Dox == "+dox") %>%
  filter(GDF11 > 0, 
         TGFB1 > 0)%>%
  mutate(GDF11 = as.factor(GDF11),
         TGFB1 = as.factor(TGFB1)) %>%
  group_by(Experiment) %>%
  mutate(new_norm_pSMAD2 = (mean_Norm_pSMAD2 - min(mean_Norm_pSMAD2)) /(max(mean_Norm_pSMAD2)-min(mean_Norm_pSMAD2))) %>%
  ungroup()
  

ggplot(temp, aes(x = GDF11, y = TGFB1, fill = new_norm_pSMAD2))+
  geom_tile()+
  facet_wrap(Experiment ~ binID, scales = "free") + 
  scale_x_discrete(drop = TRUE)+
  scale_y_discrete(drop = TRUE)+
  scale_fill_viridis_c(name = "Norm pSMAD2")
```



```{r}
temp = df$binned_boot %>%
  filter(Dox == "+dox") %>%
   # filter(GDF11 == 0 | GDF11 > 7 ,
   #        TGFB1 == 0 | TGFB1 > 0.9) %>%
  mutate(GDF11 = as.factor(GDF11),
         TGFB1 = as.factor(TGFB1)) %>%
  #filter(Experiment == "2023-07-19") %>%
  group_by(Experiment) %>%
  mutate(new_norm_pSMAD2 = (median_Norm_pSMAD2 - min(median_Norm_pSMAD2)) /(max(median_Norm_pSMAD2)-min(median_Norm_pSMAD2))) %>%
  ungroup()
  

ggplot(temp, aes(x = GDF11, y = TGFB1, fill = new_norm_pSMAD2))+
  geom_tile()+
  facet_grid(Experiment ~ binID, scales = "free") + 
  scale_x_discrete(drop = TRUE)+
  scale_y_discrete(drop = TRUE)+
  scale_fill_viridis_c(name = "Norm pSMAD2")
```
```{r}
ggplot(temp, aes(x = binID, y = new_norm_pSMAD2, color = Experiment))+
  geom_point()+
  facet_grid(GDF11~TGFB1)

```
```{r}
temp = df$binned_boot %>%
  filter(Dox == "+dox") %>%
   # filter(GDF11 == 0 | GDF11 > 7 ,
   #        TGFB1 == 0 | TGFB1 > 0.9) %>%
  mutate(GDF11 = as.factor(GDF11),
         TGFB1 = as.factor(TGFB1)) %>%
  #filter(Experiment == "2023-07-19") %>%
  group_by(Experiment) %>%
  mutate(new_norm_pSMAD2 = (mean_Norm_pSMAD2 - min(mean_Norm_pSMAD2)) /(max(mean_Norm_pSMAD2)-min(mean_Norm_pSMAD2))) %>%
  ungroup()
  

ggplot(temp, aes(x = GDF11, y = TGFB1, fill = new_norm_pSMAD2))+
  geom_tile()+
  facet_grid(Experiment ~ binID) + 
  scale_x_discrete(drop = TRUE)+
  scale_y_discrete(drop = TRUE)+
  scale_fill_viridis_c(name = "Min-Max Norm pSMAD2")+
  coord_equal()
```
```{r}
temp2 = temp %>%
  mutate(TGFB1 = fct_rev(TGFB1))

ggplot(temp2, aes(x = binID, y = mean_Norm_pSMAD2, color = Experiment, group = Experiment))+
  geom_point(size = 2)+
  geom_line()+
  facet_grid(TGFB1 ~   GDF11,
             labeller = labeller(
               TGFB1 = function(x) paste("TGFB1 =", x, "ng/ml"),
               GDF11 = function(x) paste("GDF11 =", x, "ng/ml")
             ))+
  xlab("HA Bin")+
  ylab("Normalized pSMAD2")

## Flipping to use GDF11 as color

ggplot(temp2, aes(x = binID, y = mean_Norm_pSMAD2, color = GDF11, group = GDF11))+
  geom_point(size = 2)+
  geom_line()+
  facet_grid(TGFB1 ~   Experiment,
             labeller = labeller(
               TGFB1 = function(x) paste("TGFB1 =", x, "ng/ml"),
               Experiment = function(x) paste("Exp", x)
             ))+
  xlab("HA Bin")+
  ylab("Normalized pSMAD2")

```
```{r}
Signal_Heatmap_df = df$binned_boot %>%
  filter(Dox == "+dox") %>%
  mutate(GDF11 = as.factor(GDF11),
         TGFB1 = as.factor(TGFB1)) %>%
  group_by(Experiment) %>%
  mutate(new_norm_pSMAD2 = (mean_Norm_pSMAD2 - min(mean_Norm_pSMAD2)) /(max(mean_Norm_pSMAD2)-min(mean_Norm_pSMAD2))) %>%
  ungroup()

ggplot(Signal_Heatmap_df, aes(x = GDF11, y = TGFB1, fill = new_norm_pSMAD2))+
  geom_tile()+
  facet_wrap(Experiment ~ binID, scales = "free", ncol = 10) + 
  scale_x_discrete(drop = TRUE)+
  scale_y_discrete(drop = TRUE)+
  scale_fill_viridis_c(name = "Norm pSMAD2")

# Save Signal_Heatmap_df for parallel processing
write.csv(Signal_Heatmap_df, "Signal_Heatmaps.csv", row.names = FALSE)
```



```{r RLS-LIC-Flow-Calculations}
temp = df$binned_boot %>%
  filter(Dox == "+dox") %>%
  mutate(GDF11 = as.factor(GDF11),
         TGFB1 = as.factor(TGFB1)) %>%
  group_by(Experiment) %>%
  mutate(new_norm_pSMAD2 = (mean_Norm_pSMAD2 - min(mean_Norm_pSMAD2)) /(max(mean_Norm_pSMAD2)-min(mean_Norm_pSMAD2))) %>%
  ungroup()



calcLIC = function(outer_edge, a, b){
  satmin = min(outer_edge)
  satmax = max(outer_edge)
  
  LIC = satmin/a - b/satmax
}

Summ_2L = temp %>%
  group_by(Experiment, binID) %>%
  summarize(a = min(new_norm_pSMAD2[TGFB1 == '0' & GDF11 == '25'],
                    new_norm_pSMAD2[TGFB1 == '3.16' & GDF11 == '0']),
            b = max(new_norm_pSMAD2[TGFB1 == '0' & GDF11 %in% c('7.9', '25')],
                    new_norm_pSMAD2[TGFB1 %in% c('1','3.16') & GDF11 == '0']),
            RLS = a/b,
            LIC = calcLIC(outer_edge = 
                            new_norm_pSMAD2[TGFB1 %in% c('1', '3.16') | 
                                              GDF11 %in% c('7.9', '25')],
                          a = a, 
                          b = b),
            satmin = min(new_norm_pSMAD2[TGFB1 == '3.16' | GDF11 == '25']),
            satmax = max(new_norm_pSMAD2[TGFB1 == '3.16' | GDF11 == '25'])
  ) %>%
  ungroup()


ggplot(Summ_2L, aes(x = LIC, y = RLS, color = Experiment))+
  geom_path()+
  geom_point(size = 2)+
  geom_text(aes(label = binID), vjust = -0.7)+
  ylim(c(0,1))+
  xlim(c(-1,1))+
  theme_classic()+
  ggtitle("With averaging outer edge")


Summ_2L = temp %>%
  group_by(Experiment, binID) %>%
  summarize(a = min(new_norm_pSMAD2[TGFB1 == '0' & GDF11 == '25'],
                    new_norm_pSMAD2[TGFB1 == '3.16' & GDF11 == '0']),
            b = max(new_norm_pSMAD2[TGFB1 == '0' & GDF11 == '25'],
                    new_norm_pSMAD2[TGFB1 == '3.16' & GDF11 == '0']),
            RLS = a/b,
            LIC = calcLIC(outer_edge = 
                            new_norm_pSMAD2[TGFB1 ==  '3.16' | 
                                              GDF11 == '25'],
                          a = a, 
                          b = b),
            satmin = min(new_norm_pSMAD2[TGFB1 == '3.16' | GDF11 == '25']),
            satmax = max(new_norm_pSMAD2[TGFB1 == '3.16' | GDF11 == '25'])
  ) %>%
  ungroup()

ggplot(Summ_2L, aes(x = LIC, y = RLS, color = Experiment))+
  geom_path()+
  geom_point(size = 2)+
  geom_text(aes(label = binID), vjust = -0.7)+
  ylim(c(0,1))+
  xlim(c(-1,1))+
  theme_classic()+
  ggtitle("Without averaging outer edge")


filt_summ = Summ_2L %>%
  filter(binID <8)

ggplot(filt_summ, aes(x = LIC, y = RLS, color = Experiment))+
  geom_path()+
  geom_point(size = 2)+
  geom_text(aes(label = binID), vjust = -0.7)+
  ylim(c(0,1))+
  xlim(c(-1,1))+
  theme_classic()+
  ggtitle("Without averaging outer edge, subset 1-7")

filt_summ = Summ_2L %>%
  filter(binID%%2 == 1)

ggplot(filt_summ, aes(x = LIC, y = RLS, color = Experiment))+
  geom_path()+
  geom_point(size = 2)+
  geom_text(aes(label = binID), vjust = -0.7)+
  ylim(c(0,1))+
  xlim(c(-1,1))+
  theme_classic()+
  ggtitle("Without averaging outer edge, odd indices only")

filt_summ = Summ_2L %>%
  filter(binID%%2 == 0)

ggplot(filt_summ, aes(x = LIC, y = RLS, color = Experiment))+
  geom_path()+
  geom_point(size = 2)+
  geom_text(aes(label = binID), vjust = -0.7)+
  ylim(c(0,1))+
  xlim(c(-1,1))+
  theme_classic()+
  ggtitle("Without averaging outer edge, even indices only")
```

```{r Seq-Eucl-Distance-RLS-LIC-Space}
## KAJ: Calculate the sequential RLS-LIC Euclidean distances for 1...7 (group 1) 
## and 7...10 (group 2).  Retain color coding by experiment.  I predict a 
## significantly larger set of distances for group 2 compared to group 1.
library(ggpubr)
# This code requires that Summ_2L is created from the previous code block

# Calculate Euclidean distance in RLS-LIC space
groupID_cutoff = 7

RLS_LIC_diff = Summ_2L %>%
  arrange(Experiment, binID) %>%
  group_by(Experiment) %>%
  mutate(
    diff_RLS = RLS - lag(RLS),
    diff_LIC = LIC - lag(LIC),
    diffID = row_number() - 1,
    Eucl_diff = sqrt(diff_RLS^2 + diff_LIC^2),
    theta = atan2(diff_RLS,diff_LIC)
  ) %>% 
  ungroup() %>%
  filter(!is.na(Eucl_diff)) %>%
  mutate(groupID =
    factor(case_when(
      diffID < groupID_cutoff ~ '1',
      diffID >= groupID_cutoff ~ '2'
    ))
  )

ggplot(RLS_LIC_diff, aes(x = groupID, y = Eucl_diff, color = Experiment)) +
  geom_point()+
  facet_wrap(~Experiment)+
  theme_classic()+
  ggtitle("Group cutoff at binID =  7")+
   stat_compare_means(
    aes(group = groupID),
    method = "wilcox.test",
    exact = TRUE,
    label = "p.format",
    comparisons = list(c('1', '2'))
  ) 

summ = RLS_LIC_diff %>%
  group_by(Experiment) %>%
  summarize(p_val = wilcox.test(Eucl_diff ~ groupID)$p.value)

```


```{r}
temp_summ = temp %>%
  group_by(Experiment, TGFB1, GDF11) %>%
  summarize(minmax = max(new_norm_pSMAD2)- min(new_norm_pSMAD2),
            diff_10_1 = new_norm_pSMAD2[binID == 10] - 
                        new_norm_pSMAD2[binID == 1]) %>%
  ungroup()


ggplot(temp_summ, aes(x = GDF11, y = TGFB1, fill = minmax))+
  geom_tile()+
  facet_wrap(~ Experiment, scales = "free", ncol = 10) + 
  scale_x_discrete(drop = TRUE)+
  scale_y_discrete(drop = TRUE)+
  scale_fill_viridis_c(name = "Range of pSMAD2 across HA bins")

ggplot(temp_summ, aes(x = GDF11, y = minmax, color = Experiment, group = Experiment))+
  geom_line()+
  geom_point(size = 2)+
  facet_grid(~TGFB1)
```
```{r}

temp2 = temp %>%
  filter(binID == 1 | binID == 5 | binID == 10)

ggplot(temp2, aes(x = GDF11, y = mean_Norm_pSMAD2, color = Experiment, group = Experiment))+
  geom_point(size = 2)+
  geom_line()+
  facet_grid(binID~TGFB1)

ggplot(temp2, aes(x = TGFB1, y = mean_Norm_pSMAD2, color = Experiment, group = Experiment))+
  geom_point(size = 2)+
  geom_line()+
  facet_grid(binID~GDF11)


```
```{r}
ggplot(temp, aes(x = binID, y = mean_Norm_pSMAD2, color = GDF11, group = GDF11))+
  geom_line()+
  geom_point(size = 2)+
  facet_grid(TGFB1~Experiment)
```
```{r}
# Trying to show that GDF11 has a larger inhibitory effect with higher coreceptor
temp_summ_GDF11 = temp %>%
  group_by(Experiment, TGFB1, binID) %>%
  summarize(diffGDF11 = max(mean_Norm_pSMAD2) - min(mean_Norm_pSMAD2)) %>%
  ungroup()

ggplot(temp_summ_GDF11, aes(x = binID, y = diffGDF11, color = Experiment, group = Experiment))+
  geom_point(size = 2)+
  geom_line()+
  facet_grid(~TGFB1)


```


